@URL = http://localhost:3000/v1/

###
POST {{URL}}creator/upcoming-accepted-project HTTP/1.1
Content-Type: application/json

{
  "crew_member_id": 1951
}

###
POST {{URL}}auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "parth9999@gmail.com",
  "password": "111111"
}