CREATE TABLE IF NOT EXISTS finance_transactions (
  finance_transaction_id INT NOT NULL AUTO_INCREMENT,
  transaction_code VARCHAR(64) NOT NULL,
  booking_id INT NULL,
  payment_id INT NULL,
  invoice_send_history_id INT NULL,
  client_user_id INT NULL,
  guest_email VARCHAR(255) NULL,
  transaction_type ENUM('client_payment', 'manual_payment', 'refund', 'adjustment', 'credit', 'creator_earning', 'platform_fee') NOT NULL DEFAULT 'client_payment',
  direction ENUM('inflow', 'outflow', 'internal') NOT NULL DEFAULT 'inflow',
  source ENUM('stripe', 'manual', 'account_credit', 'system', 'admin') NOT NULL DEFAULT 'system',
  payment_method VARCHAR(64) NULL,
  status ENUM('pending', 'paid', 'failed', 'refunded', 'void', 'cancelled') NOT NULL DEFAULT 'pending',
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  platform_fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  creator_earnings_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  gateway_fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  external_reference VARCHAR(255) NULL,
  transaction_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata_json TEXT NULL,
  created_by_user_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (finance_transaction_id),
  UNIQUE KEY uniq_finance_transaction_code (transaction_code),
  KEY idx_finance_transactions_booking (booking_id),
  KEY idx_finance_transactions_payment (payment_id),
  KEY idx_finance_transactions_status (status),
  KEY idx_finance_transactions_type (transaction_type),
  KEY idx_finance_transactions_date (transaction_date),
  CONSTRAINT fk_finance_transactions_booking FOREIGN KEY (booking_id) REFERENCES stream_project_booking(stream_project_booking_id),
  CONSTRAINT fk_finance_transactions_payment FOREIGN KEY (payment_id) REFERENCES payment_transactions(payment_id),
  CONSTRAINT fk_finance_transactions_invoice FOREIGN KEY (invoice_send_history_id) REFERENCES invoice_send_history(invoice_send_history_id),
  CONSTRAINT fk_finance_transactions_client_user FOREIGN KEY (client_user_id) REFERENCES users(id),
  CONSTRAINT fk_finance_transactions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_project_breakdowns (
  finance_project_breakdown_id INT NOT NULL AUTO_INCREMENT,
  booking_id INT NOT NULL,
  quote_id INT NULL,
  client_user_id INT NULL,
  guest_email VARCHAR(255) NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  equipment_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  platform_fee_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  platform_fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  creator_earnings_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  collected_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  outstanding_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  payment_status ENUM('unpaid', 'pending', 'partially_paid', 'paid', 'failed', 'refunded') NOT NULL DEFAULT 'unpaid',
  metadata_json TEXT NULL,
  calculated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (finance_project_breakdown_id),
  UNIQUE KEY uniq_finance_breakdown_booking (booking_id),
  KEY idx_finance_breakdowns_client (client_user_id),
  KEY idx_finance_breakdowns_status (payment_status),
  CONSTRAINT fk_finance_breakdowns_booking FOREIGN KEY (booking_id) REFERENCES stream_project_booking(stream_project_booking_id),
  CONSTRAINT fk_finance_breakdowns_client_user FOREIGN KEY (client_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_invoice_payments (
  finance_invoice_payment_id INT NOT NULL AUTO_INCREMENT,
  invoice_send_history_id INT NOT NULL,
  payment_id INT NULL,
  finance_transaction_id INT NULL,
  booking_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('pending', 'paid', 'failed', 'void') NOT NULL DEFAULT 'pending',
  paid_at DATETIME NULL,
  metadata_json TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (finance_invoice_payment_id),
  KEY idx_finance_invoice_payments_invoice (invoice_send_history_id),
  KEY idx_finance_invoice_payments_payment (payment_id),
  KEY idx_finance_invoice_payments_booking (booking_id),
  KEY idx_finance_invoice_payments_status (status),
  CONSTRAINT fk_finance_invoice_payments_invoice FOREIGN KEY (invoice_send_history_id) REFERENCES invoice_send_history(invoice_send_history_id),
  CONSTRAINT fk_finance_invoice_payments_payment FOREIGN KEY (payment_id) REFERENCES payment_transactions(payment_id),
  CONSTRAINT fk_finance_invoice_payments_transaction FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(finance_transaction_id),
  CONSTRAINT fk_finance_invoice_payments_booking FOREIGN KEY (booking_id) REFERENCES stream_project_booking(stream_project_booking_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS creator_earnings (
  creator_earning_id INT NOT NULL AUTO_INCREMENT,
  booking_id INT NOT NULL,
  creator_id INT NOT NULL,
  payment_id INT NULL,
  finance_transaction_id INT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  platform_fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  net_earning_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('pending', 'earned', 'payout_pending', 'paid', 'held', 'cancelled') NOT NULL DEFAULT 'pending',
  earned_at DATETIME NULL,
  payout_id INT NULL,
  metadata_json TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (creator_earning_id),
  KEY idx_creator_earnings_booking (booking_id),
  KEY idx_creator_earnings_creator (creator_id),
  KEY idx_creator_earnings_payment (payment_id),
  KEY idx_creator_earnings_status (status),
  CONSTRAINT fk_creator_earnings_booking FOREIGN KEY (booking_id) REFERENCES stream_project_booking(stream_project_booking_id),
  CONSTRAINT fk_creator_earnings_creator FOREIGN KEY (creator_id) REFERENCES crew_members(crew_member_id),
  CONSTRAINT fk_creator_earnings_payment FOREIGN KEY (payment_id) REFERENCES payment_transactions(payment_id),
  CONSTRAINT fk_creator_earnings_transaction FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(finance_transaction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
