CREATE TABLE IF NOT EXISTS `project_meetings` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `project_id` INT NULL,
  `created_by_user_id` INT NULL,
  `meeting_title` VARCHAR(255) NULL,
  `meeting_type` ENUM('pre_production','post_production') NOT NULL DEFAULT 'post_production',
  `meeting_status` ENUM('pending','confirmed','in_progress','change_request','completed','cancelled','rescheduled') NOT NULL DEFAULT 'pending',
  `meeting_platform` VARCHAR(50) NULL,
  `meeting_date_time` DATETIME NOT NULL,
  `meeting_end_time` DATETIME NULL,
  `description` LONGTEXT NULL,
  `meet_link` VARCHAR(1000) NULL,
  `participants_json` LONGTEXT NULL,
  `send_notification` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`meeting_id`),
  KEY `idx_project_meetings_booking` (`booking_id`),
  KEY `idx_project_meetings_project` (`project_id`),
  KEY `idx_project_meetings_created_by` (`created_by_user_id`),
  KEY `idx_project_meetings_status` (`meeting_status`),
  KEY `idx_project_meetings_datetime` (`meeting_date_time`)
);
